#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""D1 companies.industry_id を tools/taxonomy_companies.csv(=分類の唯一の正)から生成。
新・大分類/中分類 → 既存 D1 industries.id(underscore slug)へ写像。既存industriesのみ使用(新規行は作らない)。
stamp_rally(index.ts:1246)= industries JOIN companies GROUP BY i.id HAVING COUNT>=2 の分母に直結。

Usage:
  python3 tools/build_d1_industry_from_csv.py <current.json> <pseudo.json> <out.sql>
    current.json = {id: industry_id}(実会社の現状) / pseudo.json = {industry_id: n}(擬似会社)
  → 差分UPDATEのみ out.sql に出力・差分一覧と反映後の業界数(≥2)を表示。
"""
import json, csv, sys, collections

ROOT = "/Users/oscardodds/projects/10koma-shukatsu"
CSVF = f"{ROOT}/tools/taxonomy_companies.csv"

# 新・大分類 → D1 industry_id(既定)。一部は中分類で上書き。
DAI2D1 = {
    "商社": "specialty_trading",  # 総合商社は下で上書き
    "金融": "banking_insurance",
    "自動車・輸送機器": "manufacturer",      # D1 'manufacturer'(name=自動車)
    "電機・機械・重工": "electronics_precision",
    "素材・化学": "materials_chemical",
    "消費財・ヘルスケアメーカー": "consumer_goods",  # 中分類で上書き(食品/医薬)
    "IT・通信・インターネット": "it_ai_saas",
    "コンサル・シンクタンク": "consulting",
    "インフラ・エネルギー": "infra_energy",
    "建設・不動産": "real_estate",
    "運輸・物流": "transport_logistics",
    "小売・流通": "retail",
    "マスコミ・広告・エンタメ": "advertising_media",  # ゲームは下で上書き
    "教育・人材": "education_hr",
    "ディープテック・宇宙": "deeptech_space_ai",  # バイオ新素材は下で上書き
}
# 中分類による上書き(やっていることが親大分類のD1既定と別のもの)
CHU2D1 = {
    "総合商社": "sogo_shosha",
    "食品・飲料": "food_beverage",
    "医薬品・製薬": "pharma_healthcare",
    "ヘルステック（医療IT）": "pharma_healthcare",
    "ゲーム": "game_entertainment",
    "バイオ・新素材": "startup",
}

def desired_for(dai, chu):
    return CHU2D1.get(chu) or DAI2D1[dai]

def main():
    current = json.load(open(sys.argv[1]))            # {id: industry_id}
    pseudo  = json.load(open(sys.argv[2]))            # {industry_id: n}
    outsql  = sys.argv[3]
    rows = list(csv.DictReader(open(CSVF, encoding="utf-8-sig")))
    desired = {r["slug"]: desired_for(r["新・大分類"], r["新・中分類"]) for r in rows}

    # 差分
    diffs = [(cid, current.get(cid), d) for cid, d in desired.items() if current.get(cid) != d]
    name = {r["slug"]: r["社名"] for r in rows}
    print(f"=== D1 industry_id 差分(対象限定UPDATE): {len(diffs)}社 ===")
    by_move = collections.Counter((cur, new) for _, cur, new in diffs)
    for (cur, new), n in sorted(by_move.items(), key=lambda x: -x[1]):
        print(f"  {cur} -> {new}: {n}社")
    print("  明細:")
    for cid, cur, new in sorted(diffs, key=lambda x: (x[1] or '', x[2])):
        print(f"    {name.get(cid,cid):22} {cur} -> {new}")

    # 反映後の stamp_rally 業界数(≥2)予測: 実会社(desired) + 擬似(pseudo)
    real = collections.Counter(desired.values())
    total = collections.Counter()
    for k, v in real.items(): total[k] += v
    for k, v in pseudo.items(): total[k] += v
    inds = sorted([k for k, v in total.items() if v >= 2])
    print(f"\n=== 反映後の業界数(industries JOIN companies HAVING>=2) 予測: {len(inds)} ===")
    print("  ", inds)
    empties = [k for k in set(current.values()) if real.get(k, 0) + pseudo.get(k, 0) < 2]
    if empties: print("  ≥2未満に落ちる(stamp対象外):", empties)

    # 差分UPDATEのみ出力(idempotent)
    with open(outsql, "w") as f:
        f.write("-- generated by build_d1_industry_from_csv.py — targeted UPDATE only (diffs)\n")
        for cid, cur, new in diffs:
            cid_esc = cid.replace("'", "''")
            f.write(f"UPDATE companies SET industry_id='{new}' WHERE id='{cid_esc}';\n")
    print(f"\nwrote {len(diffs)} UPDATE -> {outsql}")

if __name__ == "__main__":
    main()
